projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "https://us1.prisma.sh/calvinhobbes352/server/dev"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml